import {useEffect,useState} from "react";
import {api} from "../api";
const EMPTY={sources:[],ingestions:[]};
function parseCSV(text){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return null;const split=l=>l.split(",").map(v=>v.trim().replace(/^"|"$/g,""));const columns=split(lines[0]);const rows=lines.slice(1,501).map(line=>Object.fromEntries(columns.map((c,i)=>[c,split(line)[i]??""])));return {columns,rows};}
export default function DataSources(){const [data,setData]=useState(EMPTY);const [preview,setPreview]=useState(null);const [name,setName]=useState("");const [status,setStatus]=useState("");const [error,setError]=useState("");
const load=async()=>{try{const out=await api(`/data-sources/state`);setData({sources:Array.isArray(out.sources)?out.sources:[],ingestions:Array.isArray(out.ingestions)?out.ingestions:[]});setError("");}catch(e){setData(EMPTY);setError("Data Sources API unavailable. Make sure the Sprint 3 backend is running on port 8000.");}};
useEffect(()=>{load()},[]);
async function choose(e){const f=e.target.files?.[0];if(!f)return;setName(f.name);const parsed=parseCSV(await f.text());setPreview(parsed);setStatus(parsed?`${parsed.rows.length} rows ready for ingestion`:"CSV needs a header and data rows");}
async function ingest(){if(!preview)return;try{setStatus("Ingesting...");const out=await api(`/data-sources/ingest`,{method:"POST",body:JSON.stringify({name,...preview})});setStatus(out.status==="INGESTED"?`${out.row_count} rows ingested successfully`:out.message);await load();}catch{setStatus("Ingestion failed. Check backend connection.");}}
const sources=data.sources||[],ingestions=data.ingestions||[];
return <div className="product-page"><header className="product-header"><div><p className="eyebrow">DATA FOUNDATION</p><h1>Data Sources</h1><p>Preview, validate and ingest mining datasets into the workspace.</p></div><div className="module-badge">{sources.filter(x=>x.status==="CONNECTED").length} LIVE SOURCES</div></header>{error&&<section className="source-error"><b>CONNECTION ERROR</b><span>{error}</span><button onClick={load}>Retry connection</button></section>}<div className="source-grid"><label className="upload-card"><span>⇧</span><h3>Upload mining dataset</h3><p>CSV telemetry, fleet logs, production records or maintenance history.</p><input type="file" accept=".csv,text/csv" onChange={choose}/><b>{name||"Choose CSV file"}</b></label><article className="connector-card"><p className="eyebrow">INGESTION STATUS</p><h2>{status||"Waiting for dataset"}</h2>{preview&&<><p>{preview.columns.length} columns detected</p><button onClick={ingest}>Ingest {preview.rows.length} rows →</button></>}</article></div>{preview&&<section className="source-list"><h2>Dataset preview</h2><div className="csv-preview"><table><thead><tr>{preview.columns.slice(0,8).map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{preview.rows.slice(0,5).map((r,i)=><tr key={i}>{preview.columns.slice(0,8).map(c=><td key={c}>{r[c]}</td>)}</tr>)}</tbody></table></div></section>}<section className="source-list"><h2>Connected sources & ingestion history</h2>{[...sources,...ingestions].length===0?<p className="muted">No source data loaded yet.</p>:[...sources,...ingestions].map(s=><div key={s.id}><span className="source-icon">⇅</span><b>{s.name}<small>{s.type||"CSV DATASET"}</small></b><span>{s.records??`${s.row_count??0} rows`}</span><i>{s.status}</i></div>)}</section></div>}
