import {useEffect,useState} from "react";
import {useNavigate} from "react-router-dom";
import {api} from "../api";
const steps=[
 ["01","LIVE FLEET","Start the haul-cycle stream and watch pit-to-crusher operations."],
 ["02","DETECT","T14 brake degradation crosses the operational threshold."],
 ["03","EXPLAIN","Causal Intelligence maps route pressure, queue growth and production impact."],
 ["04","DECIDE","MineMind ranks counterfactual actions and recommends fleet rebalancing."],
 ["05","ACT","Operator executes the intervention and T14 enters maintenance."],
 ["06","VERIFY","Risk and predicted loss fall while the incident moves through recovery."],
];
export default function DemoCenter(){const nav=useNavigate();const [busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[status,setStatus]=useState({stage:0,simulation:"CONNECTING"});async function load(){try{setStatus(await api('/workspace/demo-status'))}catch{}}useEffect(()=>{load();const i=setInterval(load,1200);return()=>clearInterval(i)},[]);async function launch(){setBusy(true);setMsg("");try{await api('/workspace/demo-launch',{method:'POST'});setMsg('OPERATIONAL DEMO IS LIVE');await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}const next=status.stage>=6?'/app/incidents':status.stage>=4?'/app/decision':status.stage>=3?'/app/causal':'/app/fleet';const nextLabel=status.stage>=6?'REVIEW AUDIT TRAIL':status.stage>=4?'OPEN DECISION ENGINE':status.stage>=3?'REVIEW CAUSAL INTELLIGENCE':'OPEN LIVE FLEET';return <div className="product-page"><header className="product-header"><div><p className="eyebrow">GUIDED OPERATIONS</p><h1>Mine Operations Journey</h1><p>A controlled end-to-end scenario across fleet telemetry, causal AI, decisions and recovery.</p></div><div className="module-badge">{status.simulation}</div></header><section className="demo-launch-card"><div><small>DEMO WORKSPACE</small><h2>Launch the operational scenario</h2><p>Loads the sample shift dataset, resets the mine scenario and starts the live fleet stream.</p></div><button disabled={busy} onClick={launch}>{busy?'LAUNCHING...':'LAUNCH DEMO →'}</button>{msg&&<strong>{msg}</strong>}</section><section className="demo-journey-grid">{steps.map((x,i)=><article key={x[0]} className={i<status.stage?'demo-step-active':''}><span>{x[0]}</span><small>{x[1]}</small><h3>{x[2]}</h3></article>)}</section><section className="demo-live-state"><div><span>SIMULATION</span><strong>{status.simulation}</strong></div><div><span>JOURNEY STAGE</span><strong>{Math.min(status.stage,6)} / 6</strong></div><div><span>ACTIVE INCIDENT</span><strong>{status.incident_id||'MONITORING'}</strong></div><button onClick={()=>nav(next)}>{nextLabel} →</button></section></div>}
