import { Link } from "react-router-dom";
export default function Landing(){return <div className="marketing">
 <nav className="marketing-nav"><b><span>M</span> MINEMIND</b><div><a href="#platform">Platform</a><a href="#workflow">How it works</a><a href="#team">Team</a><Link to="/login">Sign in</Link><Link className="primary-link" to="/signup">Start demo</Link></div></nav>
 <section className="hero"><div><p className="eyebrow">UNIFIED MINE OPERATIONS INTELLIGENCE</p><h1>Know what is happening.<br/><em>Know why.</em><br/>Act before production stops.</h1><p>MineMind unifies fleet telemetry, digital twin context, causal AI, predictive risk and ore traceability into one operational command layer for modern mines.</p><div className="hero-actions"><Link className="cta" to="/signup">Launch operations demo →</Link><a href="#platform">Explore platform</a></div><div className="trust-row"><span>LIVE FLEET</span><span>CAUSAL AI</span><span>DIGITAL TWIN</span><span>ORE PROVENANCE</span></div></div><div className="hero-console"><div className="console-top"><span>JABALPUR DEMO MINE</span><i>● LIVE</i></div><div className="hero-grid"><article><small>PRODUCTION</small><strong>840 MT/H</strong><b>+8.4%</b></article><article><small>ACTIVE FLEET</small><strong>5 / 5</strong><b>100%</b></article><article><small>DISPATCH RISK</small><strong>6%</strong><b>LOW</b></article><article><small>TRACED ORE</small><strong>225 MT</strong><b>VERIFIED</b></article></div><div className="signal"><span>⚡</span><div><small>CAUSAL SIGNAL</small><strong>T14 brake degradation can propagate to R1 queue pressure</strong><p>MineMind is monitoring the operational stream.</p></div></div></div></section>
 <section id="platform" className="marketing-section"><p className="eyebrow">ONE OPERATING LAYER</p><h2>From pit to decision, one connected system.</h2><div className="feature-grid">{[["01","Fleet Operations","Track assignments, payload, routes, health and haul cycles in real time."],["02","Live Digital Twin","See the mine, fleet and equipment state in one spatial operational view."],["03","Causal Intelligence","Move beyond alerts. Understand how one failure propagates across production."],["04","Decision Engine","Compare counterfactual actions and execute the best operational response."],["05","Ore Traceability","Create a digital custody trail from pit loading to stockyard inventory."],["06","Vision Intelligence","Turn camera detections into operational events and safety context."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
 <section id="workflow" className="workflow"><p className="eyebrow">END-TO-END WORKFLOW</p><h2>Sense → understand → decide → recover.</h2><div>{["INGEST","SIMULATE","DETECT","EXPLAIN","DECIDE","ACT","VERIFY"].map((x,i)=><span key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</span>)}</div></section>
 <section id="team" className="final-cta"><p className="eyebrow">BUILT FOR OPERATIONAL TEAMS</p><h2>Run the mine as one intelligent system.</h2><p>Operations managers, dispatch teams, reliability engineers and plant teams get a shared operational truth.</p><Link className="cta" to="/signup">Enter MineMind →</Link></section>
 <footer>MINEMIND 3.0 <span>Unified Mine Operations Intelligence</span></footer>
 </div>}
