import {useEffect,useMemo,useState} from "react";
import {api,apiFetch} from "../api";
export default function VisionIntelligence(){
 const [file,setFile]=useState(null),[result,setResult]=useState(null),[triage,setTriage]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const url=useMemo(()=>file?URL.createObjectURL(file):null,[file]);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
 async function analyze(){setBusy(true);setError("");setResult(null);setTriage(null);try{
  const form=new FormData();form.append("file",file);
  const r=await apiFetch('/vision/analyze',{method:'POST',body:form});
  const data=await r.json().catch(()=>({})); if(!r.ok)throw new Error(data.detail||`Analysis failed (${r.status})`);
  setResult(data); const eventId=data.event?.event_id; if(eventId){const t=await api(`/vision/events/${eventId}/triage`,{method:'POST'});setTriage(t)}
 }catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="product-page"><header className="product-header"><div><p className="eyebrow">VISION INTELLIGENCE</p><h1>YOLO Mine Camera Intelligence</h1><p>Run real object detection on uploaded mine footage and write the result to the operational incident ledger.</p></div><div className="module-badge">REAL YOLO INFERENCE</div></header><div className="vision-layout"><section className="vision-stage">{file?<><video src={url} controls/><div className="vision-overlay">UPLOAD-01 · VIDEO ANALYSIS</div></>:<label><span>◉</span><h2>Upload mine video</h2><p>Use an MP4 clip from a haul road, pit or crusher area.</p><input type="file" accept="video/*" onChange={e=>{setFile(e.target.files[0]);setResult(null);setTriage(null);setError("")}}/><b>Select video</b></label>}</section><aside className="vision-panel"><p className="eyebrow">YOLO INFERENCE PIPELINE</p><h2>Operational detections</h2><button disabled={!file||busy} onClick={analyze}>{busy?'Running YOLO on sampled frames...':'Run YOLO analysis →'}</button>{busy&&<p className="muted">First run may download the YOLO model. Keep backend and internet running.</p>}{error&&<p className="muted">Analysis error: {error}</p>}{result?<div className="detections"><article><small>MODEL</small><p>{result.model} · REAL INFERENCE · {result.frames_sampled}/{result.frames_total} FRAMES SAMPLED</p></article>{(result.detections||[]).map(x=><div key={x.label}><span>{x.label.replaceAll('_',' ')}</span><strong>{x.count}</strong><b>{x.confidence}%</b></div>)}{!result.detections?.length&&<p className="muted">No configured objects detected above confidence threshold.</p>}<article><small>INCIDENT LEDGER EVENT · {result.event?.event_id}</small><p>{result.description}</p></article>{triage&&<article className="vision-triage"><small>AI TRIAGE · {triage.priority}</small><strong>{triage.classification?.replaceAll("_"," ")}</strong><p>{triage.recommended_action}</p><b>OWNER · {triage.owner}</b></article>}</div>:<p className="muted">Upload a clip and run YOLO. Detection counts and confidence come from the model, not hard-coded demo values.</p>}</aside></div></div>
}
