import { BrowserRouter, Routes, Route, Navigate, Outlet } from "react-router-dom";
import { lazy, Suspense } from "react";
import DataSources from "./pages/DataSources";
import AppErrorBoundary from "./components/AppErrorBoundary";
import Sidebar from "./components/Sidebar"; import AppTopbar from "./components/AppTopbar"; import GuidedDemo from "./components/GuidedDemo";
const pages={Landing:lazy(()=>import("./pages/Landing")),Auth:lazy(()=>import("./pages/Auth")),CommandCenter:lazy(()=>import("./pages/CommandCenter")),FleetOperations:lazy(()=>import("./pages/FleetOperations")),DigitalTwin:lazy(()=>import("./pages/DigitalTwin")),CausalIntelligence:lazy(()=>import("./pages/CausalIntelligence")),DecisionEngine:lazy(()=>import("./pages/DecisionEngine")),Interventions:lazy(()=>import("./pages/Interventions")),OreTraceability:lazy(()=>import("./pages/OreTraceability")),PredictiveAnalytics:lazy(()=>import("./pages/PredictiveAnalytics")),IncidentHistory:lazy(()=>import("./pages/IncidentHistory")),VisionIntelligence:lazy(()=>import("./pages/VisionIntelligence")),Settings:lazy(()=>import("./pages/Settings")),DemoCenter:lazy(()=>import("./pages/DemoCenter"))};
const P=({name,...props})=>{const C=pages[name];return <AppErrorBoundary><Suspense fallback={<div className="route-loading"><div className="cc-loader"></div><p>LOADING MINEMIND MODULE...</p></div>}><C {...props}/></Suspense></AppErrorBoundary>};
function ProtectedLayout(){const session=localStorage.getItem("minemind_session");let parsed=null;try{parsed=JSON.parse(session||"null")}catch{}if(!parsed?.token)return <Navigate to="/login" replace/>;return <div className="app-shell"><Sidebar/><div className="workspace-shell"><AppTopbar/><main className="app-main"><Outlet/></main></div><GuidedDemo/></div>}
export default function App(){return <BrowserRouter><Routes><Route path="/" element={<P name="Landing"/>}/><Route path="/login" element={<P name="Auth" mode="login"/>}/><Route path="/signup" element={<P name="Auth" mode="signup"/>}/><Route element={<ProtectedLayout/>}><Route path="/app" element={<P name="CommandCenter"/>}/><Route path="/app/demo" element={<P name="DemoCenter"/>}/><Route path="/app/fleet" element={<P name="FleetOperations"/>}/><Route path="/app/digital-twin" element={<P name="DigitalTwin"/>}/><Route path="/app/causal" element={<P name="CausalIntelligence"/>}/><Route path="/app/decision" element={<P name="DecisionEngine"/>}/><Route path="/app/interventions" element={<P name="Interventions"/>}/><Route path="/app/traceability" element={<P name="OreTraceability"/>}/><Route path="/app/predictive" element={<P name="PredictiveAnalytics"/>}/><Route path="/app/incidents" element={<P name="IncidentHistory"/>}/><Route path="/app/data-sources" element={<AppErrorBoundary><DataSources/></AppErrorBoundary>}/><Route path="/app/vision" element={<P name="VisionIntelligence"/>}/><Route path="/app/settings" element={<P name="Settings"/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes></BrowserRouter>}
